# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Release

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Make scripts executable
      run: chmod a+x ./pack.sh ; chmod a+x ./upload.sh
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build and pack
      run: sh ./pack.sh linux-x64 amd64 

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release ID
      id: get_release_id
      run: echo "RELEASE_ID=${{ steps.create_release.ouputs.release_id }}"

    - name: Upload Deb Packages
      run: ./upload.sh
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_ID: ${{ steps.get_release_id.outputs.RELEASE_ID }}
